kind: Authenticate
apiVersion: api.ibm.com/v1
metadata:
  name: Authenticate-fvk1n
  namespace: Accounts-v3
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  namespace: client
  operation:
    subscription: {}
