kind: InvokeOpenAiModels
apiVersion: api.ibm.com/v1
metadata:
  name: InvokeOpenAiModels-fvk1n
  namespace: Accounts-v3
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  apiKeySecret: placeholder-api-key
  tlsClientProfile: tls-client-profile-default:1.0.0
  cachePolicy: disabled
  projectId: proj_8JMF7sdaFR7JZ59Tr7IhDYjk
