kind: Plan
apiVersion: api.ibm.com/v1
metadata:
  name: plan-openai-fvk1n
  namespace: Accounts-v3
  version: '1.0'
  tags: []
  description: ''
spec:
  qos:
    withQuota:
      openai-token-weighted:
        - $ref: Accounts-v3:openai-token-weighted-fvk1n:1.0
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        apis:
          - $ref: Accounts-v3:api-openai-fvk1n:1.0
            operations:
              - path: /chat/completions
                method: post
              - path: /embeddings
                method: post
              - path: /models
                method: get
              - path: /models/{a_model_id}
                method: get
        telemetry: {}
    dp-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        apis:
          - $ref: Accounts-v3:api-openai-fvk1n:1.0
            operations:
              - path: /chat/completions
                method: post
              - path: /embeddings
                method: post
              - path: /models
                method: get
              - path: /models/{a_model_id}
                method: get
