kind: Telemetry
apiVersion: api.ibm.com/v1
metadata:
  name: Telemetry-fvk1n
  namespace: Accounts-v3
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  verbosity:
    - level: basic
      onSuccessTrimTo: normal
      inboundLevel: basic
      outboundLevel: basic
      operations:
        - path: /chat/completions
          method: POST
        - path: /embeddings
          method: POST
        - path: /models
          method: GET
        - path: /models/{a_model_id}
          method: GET
