kind: Quota
apiVersion: api.ibm.com/v1
metadata:
  name: watsonx-token-weighted-hy666
  namespace: Finance-OAuth-LLM
  version: '1.0'
  description: ''
  tags:
    - env:production
    - platform:watsonx
  domain: ai-platform
spec:
  maxRequest: 1500
  interval: 10s
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        weightExpr: $variable('aiGeneratedTokenCount')
        exceedAction: return429
        intervalOffset: 0
        dynamicValue: ''
