kind: Throw
apiVersion: api.ibm.com/v1
metadata:
  name: Throw-hy666
  namespace: Finance-OAuth-LLM
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  error:
    CustomError:
      message: Token limit exceeded
      messageType: plain
      status: 429
