kind: Parse
apiVersion: api.ibm.com/v1
metadata:
  name: Parse-jyS17
  namespace: risk-api
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  documentType:
    detectByContentType: {}
  input: response
