kind: LLMProvider
apiVersion: api.ibm.com/v1
metadata:
  name: watsonx-risk-llm
  namespace: Risk-service
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
  domain: ai-platform
spec:
  provider:
    type: watsonx
    operations:
      - InvokeWatsonxModels
      - InvokeWatsonxTextGen
      - InvokeWatsonxTokenize
    apiKeySecret: mWhXPsuakfwu4GKFVk56vOxhhK6jXuX36_2W59awP0oF
    tlsClientProfile: sample-tls-client-profile:1.0.0
    inputMessage: request
    cachePolicy:
      cache:
        expire:
          static:
            seconds: 60
        scope:
          narrowScope: {}
        ignoreControlDirectives: true
    projectId: 3e55b663-335e-4f81-b47f-0ec0b272249f
    region: us-south
    opVersion: '2024-03-14'
  product:
    $ref: Risk-service:product-watsonx-risk-llm-pf2ba:1.0
