kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: banking-with-bob-freeflowpolicysequence-80qnw
  namespace: Banking-with-BOB
  version: "1.0"
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  main:
    - $ref: Banking-with-BOB:invoke-80qnw:1.0
  monitoring:
    $ref: Banking-with-BOB:telemetry-80qnw:1.0
