kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: invoke-80qnw
  namespace: Banking-with-BOB
  version: "1.0"
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  endpoint:
    http:
      target:
        tlsClientProfile: sample-tls-client-profile:1.0.0
        url: "'https://api.bank.com/v1' & $pathAndQuery()"
        urlType: jsonata
        persistentConnections: false
        timeout: 30
        decompressResponse: true
        followRedirects: false
        chunkedUpload: false
