kind: MCPServer
apiVersion: api.ibm.com/v1
metadata:
  name: accounts-api-server-zp324
  namespace: Bob-Banking-apis
  version: "1.0"
  tags: []
  labels:
    origin: mcp-rest
spec:
  title: Accounts API MCP Server
  protocolVersion: V2025_11_25
  quota:
    $ref: Bob-Banking-apis:bob-banking-apis-quota-zp324:1.0
  policy-sequence:
    - $ref: Bob-Banking-apis:bob-banking-apis-freeflowpolicysequence-zp324:1.0
  capabilities:
    tools:
      - $ref: Bob-Banking-apis:accounts-api-tool-zp324:1.0
