kind: MCPServer
apiVersion: api.ibm.com/v1
metadata:
  name: customer-api-server-saqow
  namespace: Bob-Banking-apis
  version: "1.0"
  tags: []
  labels:
    origin: mcp-rest
spec:
  title: Customer API MCP Server
  protocolVersion: V2025_11_25
  quota:
    $ref: Bob-Banking-apis:bob-banking-apis-quota-saqow:1.0
  policy-sequence:
    - $ref: Bob-Banking-apis:bob-banking-apis-freeflowpolicysequence-saqow:1.0
  capabilities:
    tools:
      - $ref: Bob-Banking-apis:customer-api-tool-saqow:1.0
