kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: invoke-5wtzu
  namespace: account-MCP
  version: "1.0"
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  endpoint:
    http:
      target:
        tlsClientProfile: sample-tls-client-profile:1.0.0
        url: "'https://banking-accounts-management-api-server-tfp5g-demo-ce.nanogw.52.1\
          18.209.186.nip.io' & $pathAndQuery()"
        urlType: jsonata
        persistentConnections: false
        timeout: 30
        decompressResponse: true
        followRedirects: false
        chunkedUpload: false
