kind: Quota
apiVersion: api.ibm.com/v1
metadata:
  name: customer-authentication-quota-rojeg
  namespace: customer-authentication
  version: '1.0'
  tags: []
spec:
  maxRequest: 1
  interval: 1m
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        exceedAction: return429
