kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: bob-banking-freeflowpolicysequence-4mryx
  namespace: BOB-Banking
  version: "1.0"
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  main:
    - $ref: BOB-Banking:invoke-4mryx:1.0
  monitoring:
    $ref: BOB-Banking:telemetry-4mryx:1.0
