kind: MCPServer
apiVersion: api.ibm.com/v1
metadata:
  name: loans-api-server-dprtz
  namespace: BOB-Banking
  version: "1.0"
  tags: []
  labels:
    origin: mcp-rest
spec:
  title: Loans API MCP Server
  protocolVersion: V2025_11_25
  quota:
    $ref: BOB-Banking:bob-banking-quota-dprtz:1.0
  policy-sequence:
    - $ref: BOB-Banking:bob-banking-freeflowpolicysequence-dprtz:1.0
  capabilities:
    tools:
      - $ref: BOB-Banking:loans-api-tool-dprtz:1.0
