kind: InvokeWatsonxTokenize
apiVersion: api.ibm.com/v1
metadata:
  name: InvokeWatsonxTokenize-t5llf
  namespace: payments-service
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  region: us-south
  opVersion: placeholder-op-version
  tlsClientProfile: tls-client-profile-default:1.0.0
  projectId: 9e9174d9-ecbf-492f-abbc-0fa9a8ea923b
  inputMessage: request
  outputMessage: response
  cachePolicy: disabled
