kind: LLMProvider
apiVersion: api.ibm.com/v1
metadata:
  name: watsonx-payments-llm
  namespace: payments-service
  version: "1.0"
  tags: []
  labels:
    gatewayTypes:
      - nano
  domain: ai-platform
spec:
  provider:
    type: watsonx
    operations:
      - InvokeWatsonxModels
      - InvokeWatsonxTextGen
      - InvokeWatsonxTokenize
    apiKeySecret: 5YoCq_IZkeOe71sLyLlubpQfIygXvEPJ_-x-2s0M0lAq
    tlsClientProfile: sample-tls-client-profile:1.0.0
    inputMessage: request
    cachePolicy:
      cache:
        expire:
          static:
            seconds: 60
        scope:
          narrowScope: {}
        ignoreControlDirectives: true
    projectId: 9e9174d9-ecbf-492f-abbc-0fa9a8ea923b
    region: us-south
    opVersion: "2024-03-14"
  product:
    $ref: payments-service:product-watsonx-payments-llm-t5llf:1.0
