kind: MCPServer
apiVersion: api.ibm.com/v1
metadata:
  name: payments-api-server-e21my
  namespace: Banking-APIs
  version: "1.0"
  tags: []
  labels:
    origin: mcp-rest
spec:
  title: Payments API MCP Server
  protocolVersion: V2025_11_25
  quota:
    $ref: Banking-APIs:banking-apis-quota-e21my:1.0
  policy-sequence:
    - $ref: Banking-APIs:banking-apis-freeflowpolicysequence-e21my:1.0
  capabilities:
    tools:
      - $ref: Banking-APIs:payments-api-tool-e21my:1.0
